export const EXCHANGE_TYPES = {
    SET_CONTRACT_ADDRESS: "SET_CONTRACT_ADDRESS",
    SET_CONTRACT_PROVIDER: "SET_CONTRACT_PROVIDER",
    SET_ERROR: "SET_ERROR",
    SET_ERROR_MSG: "SET_ERROR_MSG",
    SET_LOADING:"SET_LOADING"
}