export const EXCHANGE_TYPES = {
    SET_CONTRACT_ADDRESS: "SET_CONTRACT_ADDRESS",
    SET_CONTRACT_PROVIDER: "SET_CONTRACT_PROVIDER",
    SET_ERROR: "SET_ERROR",
    SET_ERROR_MSG: "SET_ERROR_MSG",
    SET_LOADING: "SET_LOADING",
    SET_BALANCE_VARMA: "SET_BALANCE_VARMA",
    SET_BALANE_TOKEN2: "SET_BALANE_TOKEN2",
    SET_ALL_ORDER_EVENTS: "SET_ALL_ORDER_EVENTS",
    SET_ALL_ORDER_EVENTS_ACTIVE: "SET_ALL_ORDER_EVENTS_ACTIVE",
    SET_BUY_OR_SELL_DONE: "SET_BUY_OR_SELL_DONE",
    SET_ALL_BUY_ORDERS: "SET_ALL_BUY_ORDERS",
    SET_ALL_SELL_ORDERS: "SET_ALL_SELL_ORDERS",
    SET_CANDLE_CHART:"SET_CANDLE_CHART"
}