export const WALLET_TYPES = {
    SET_PROVIDER: 'SET_PROVIDER',
    SET_WALLETADDRESS: 'SET_WALLETADDRESS',
    SET_ERROR: "SET_ERROR",
    SET_ERROR_MSG: "SET_ERROR_MSG",
    SET_LOADING: "SET_LOADING",
    SET_NETWORK: "SET_NETWORK",
    SET_BALANCE: "SET_BALANCE",
    SET_SYMBOL:"SET_SYMBOL"
}