export const TOKEN_TYPES = {
    SET_VARMA_PROVIDER:"SET_VARMA_PROVIDER",
    SET_USDT_PROVIDER:"SET_USDT_PROVIDER",
    SET_INRT_PROVIDER:"SET_INRT_PROVIDER",
    SET_ERROR: "SET_ERROR",
    SET_ERROR_MSG: "SET_ERROR_MSG",
    SET_LOADING:"SET_LOADING",
    SET_TOKEN_STATE:"SET_TOKEN_STATE",
    SET_VARMA_TOKEN_BALANCE: "SET_VARMA_TOKEN_BALANCE",
    SET_TOKEN2_BALANCE: "SET_TOKEN2_BALANCE"
}