export const TOKEN_TYPES = {
    SET_CONTRACT_ADDRESS: "SET_CONTRACT_ADDRESS",
    SET_CONTRACT_PROVIDER: "SET_CONTRACT_PROVIDER",
    SET_TOKEN_NAME: "SET_TOKEN_NAME",
    SET_TOKEN_SYMBOL: "SET_TOKEN_SYMBOL",
    SET_ERROR: "SET_ERROR",
    SET_ERROR_MSG: "SET_ERROR_MSG",
    SET_LOADING:"SET_LOADING"
}